#162199452 Trending articles
andela/haven-ah-frontend pull request #8
Opened 2018-11-30 07:24 UTC by wiztemple

#### What does this PR do?
- Display top 6 trending articles

#### Description of tasks to be completed
- create cards for displaying trending articles
- create a class component for displaying it
- write the scss for aesthetics
- write test for the component

#### How can this be manually tested?
- on the terminal run git clone https://github.com/andela/haven-ah-frontend.git.
- run git checkout ft-design-trending-article-162199452
- run npm install to install the npm packages.
- run npm test to run the unit and integration tests.

#### What are the relevant Pivotal Tracker stories?
- _[#162199452]()_

#### Screenshots(if appropriate)
<img width="1424" alt="screenshot 2018-12-03 at 4 49 54 pm" src="https://user-images.githubusercontent.com/25081005/49384558-8a397880-f71b-11e8-8912-169be3d60293.png">

2018-12-03 16:11 UTC, ucheg6 commented
Great Job @wiztemple 👍

2018-12-03 17:26 UTC, seyi-adeleke requested changes

2018-12-03 17:26 UTC, seyi-adeleke commented on public/styles/App.scss
> -$heading-font-family: 'Playfair Display', sans-serif;
Why did you remove these?

2018-12-05 10:15 UTC, seyi-adeleke commented on src/actionTypes/trendingActionType.js
> +
Remove this excess space

2018-12-05 10:15 UTC, seyi-adeleke commented on src/actions/trendingArticlesAction.js
> +
same here

2018-12-05 10:16 UTC, seyi-adeleke commented on src/components/trendingsection/TrendingCard.jsx
> +const { log } = console;
remove this log

2018-12-05 10:16 UTC, seyi-adeleke commented on src/components/trendingsection/TrendingCard.jsx
> +  log('The images: ', images);
here

2018-12-05 10:16 UTC, seyi-adeleke commented on src/components/trendingsection/TrendingCard.jsx
> +import timeFormatter from '../../helpers/timeFormatter.jsx';
should this be .jsx?

2018-12-05 10:18 UTC, seyi-adeleke commented on src/components/trendingsection/TrendingCard.jsx
> +  readtime: PropTypes.number,
add `.isRequired` to all the proptypes,
`PropTypes.number .isRequired`

2018-12-05 10:24 UTC, seyi-adeleke requested changes

2018-12-05 10:24 UTC, seyi-adeleke commented on src/components/trendingsection/TrendingSection.jsx
> +import 'bulma/css/bulma.min.css';
You shouldnt be importing bulma here

2018-12-05 10:24 UTC, seyi-adeleke commented on src/components/trendingsection/TrendingSection.jsx
> +    console.log(articles);
Remove this console.log

2018-12-05 10:24 UTC, seyi-adeleke commented on src/components/trendingsection/TrendingSection.scss
> +    color: #a0a0a0;
lets use variables for all our colors

2018-12-05 10:24 UTC, seyi-adeleke commented on src/components/trendingsection/TrendingSection.scss
> +
fix all the indentation issues

2018-12-05 10:24 UTC, seyi-adeleke commented on src/routes.js
> +
Remove this space

2018-12-05 13:35 UTC, seyi-adeleke commented on src/App.jsx
> +import '../public/styles/colors.scss';
is this import necessary?

2018-12-05 13:51 UTC, PriscillaSam commented on public/styles/colors.scss
> +$dark-gray: #a0a0a0;
Great work @wiztemple

2018-12-05 14:57 UTC, TheoOkafor commented on public/styles/colors.scss
> +$dark-gray: #a0a0a0;
nice

2018-12-05 15:31 UTC, seyi-adeleke approved these changes

2018-12-05 15:31 UTC, merged